name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Cache pipenv
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run scrapper
        run: |
          pipenv run python main.py 5 500 -l warning

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.current-time.outputs.time }}"
          body: "${{ steps.current-time.outputs.time }}"
          files: |
            ./additives.json
        env:
          GITHUB_REPOSITORY: kevinrpb/additives-scrapper
